config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

  def index
    @articles = Article.all
  end

  def show
    @comment = @article.comments.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: "Article: '#{@article.title}' saved successfully."
    else
      flash[:alert] = "Failed to save article."
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article has been updated."
    else
      flash[:alert] = "Failed to update article."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other, notice: "Article has been deleted."
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def record_not_found
      redirect_to articles_path, alert: "Record does not exist."
    end

    def invalid_foreign_key
      redirect_to articles_path, alert: "Unable to delete article. Still referenced from comments."
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @article.comments
  end

  def show; end

  def create
    @comment = @article.comments.create(comment_params)

    if @comment.persisted?
      redirect_to article_path(@article), notice: "Comment saved successfully."
    else
      flash.now[:alert] = "Failed to save comment."
      render "articles/show", status: :unprocessable_entity
    end
  end

  def edit; end
  
  def update
    if @comment.update(comment_params)
      redirect_to @article, notice: "Comment has been updated."
    else
      flash[:alert] = "Failed to update comment."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    redirect_to @article, status: :see_other, notice: "Comment has been deleted."
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<%= link_to "Back to Home", articles_path, type: "button", class: "btn btn-primary" %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to "#{article.title}, id: #{article.id}", article %>
    </li>
  <% end %>
</ul>

<%= link_to "Create New Article", new_article_path, type: "button", class: "btn btn-primary" %>

<br>

<%= form_with url: destroy_user_session_path, method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
  <button type="submit" class="btn btn-danger">Sign out</button>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<%= link_to "Back to Home", articles_path, type: "button", class: "btn btn-primary" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1> <h6><%= link_to "Edit", edit_article_path(@article) %></h6>

<p><%= @article.body %></p>

<%= form_with url: article_path(@article), method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
  <button type="submit" class="btn btn-danger">Delete</button>
<% end %>
<br>
<%= link_to "Back to Home", articles_path, type: "button", class: "btn btn-primary" %>

<h2>Comments</h2>
<%= render @article.comments.select(&:persisted?) %>

<h2>Add a comment:</h2>
<%= render "comments/form", article: @article, comment: @comment %>

app/views/comments/_comment.html.erb
<h6><%= link_to "View", [comment.article, comment] %></h6>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<%= form_with url: [comment.article, comment], method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
  <button type="submit" class="btn btn-danger">Delete</button>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [article, comment]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
    <% @comment.errors.full_messages_for(:commenter).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @comment.errors.full_messages_for(:body).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", article: @article, comment: @comment %>

<%= link_to "Back", articles_path(@article), type: "button", class: "btn btn-primary" %>

app/views/comments/index.html.erb
<h1>All Comments</h1>

<% @comments.each do |comment| %>
  <p> <%= comment.commenter  %> </p>
  <p> <%= comment.body  %> </p>
<% end %>

app/views/comments/show.html.erb
<h3><%= @comment.commenter %></h3>

<p><%= @comment.body %></p>

<h6><%= link_to "Edit", edit_article_comment_path(@article) %></h6>

<%= link_to "Back to Article", article_path, type: "button", class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "New Rails App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div style="text-align: center" class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>